services:
  api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:latest
    restart: always
    depends_on:
      - redis
      - postgres
    network_mode: host
    env_file:
      - .env
    environment:
      - SERVER_PORT=8080
      - DATABASE_CONNECTION_URI=postgresql://evolution:evolution@localhost:5432/evolution_db?schema=evolution_api
      - CACHE_REDIS_URI=redis://localhost:6379/6
    volumes:
      - evolution_instances:/evolution/instances

  redis:
    container_name: evolution_redis
    image: redis:latest
    restart: always
    command: >
      redis-server --port 6379 --appendonly yes
    network_mode: host
    volumes:
      - evolution_redis:/data

  postgres:
    container_name: evolution_postgres
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=evolution_db
      - POSTGRES_USER=evolution
      - POSTGRES_PASSWORD=evolution
    command:
      - postgres
      - -c
      - max_connections=1000
      - -c
      - listen_addresses=*
    network_mode: host
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:
